version: '2'
services:
    timelocation-app:
        image: timelocation
        external_links:
            - timelocation-postgresql:postgresql
            - timelocation-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/timeLocation
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    timelocation-postgresql:
        extends:
            file: postgresql.yml
            service: timelocation-postgresql
    timelocation-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: timelocation-elasticsearch
